services:
  wordpress:
    build:
      context: .
      dockerfile: docker/wordpress.dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    container_name: pof_wordpress
    depends_on:
      - db
      - phpmyadmin
    ports: 
      - 8080:80

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: pofuser
      WORDPRESS_DB_PASSWORD: pofpass
      WORDPRESS_DB_NAME: poweroffamilies
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_HOME: http://localhost:8080
      WORDPRESS_SITEURL: http://localhost:8080
      # WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      WORDPRESS_SCRIPT_DEBUG: ${WORDPRESS_DEBUG:-false}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', getenv('WORDPRESS_HOME', ''));
        define('WP_SITEURL', getenv('WORDPRESS_SITEURL', ''));
        define('SCRIPT_DEBUG', getenv('WORDPRESS_SCRIPT_DEBUG', ''));
    volumes:
      - ./wordpress:/var/www/html
      - type: bind
        source: ./power-of-families
        target: /var/www/html/wp-content/themes/power-of-families
      # - type: bind
      #   source: ./pof-bloom-plugin
      #   target: /var/www/html/wp-content/plugins/pof-bloom
      - ./phpunit.xml.dist:/var/www/html/wp-content/themes/power-of-families/phpunit.xml
      - ./.phpcs.xml.dist:/var/www/html/wp-content/themes/power-of-families/.phpcs.xml
      - ./bin:/var/www/html/bin

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: '33'
    entrypoint: wp
    command: "--info"
    container_name: pof_wpcli
    volumes:
      - ./wordpress:/var/www/html
      - type: bind
        source: ./power-of-families
        target: /var/www/html/wp-content/themes/power-of-families
    working_dir: /var/www/html
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: pofuser
      WORDPRESS_DB_PASSWORD: pofpass
      WORDPRESS_DB_NAME: poweroffamilies
      PHP_MEMORY_LIMIT: 20G
      WP_MEMORY_LIMIT: 20G
      WP_CLI_PHP_MEMORY_LIMIT: 4G

  db:
    image: mariadb:${MARIA_DB_VERSION:-10.11.13}
    container_name: pof_db
    restart: always
    environment:
      MYSQL_DATABASE: poweroffamilies
      MYSQL_USER: pofuser
      MYSQL_PASSWORD: pofpass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-backups:/tmp/backups

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: pof_phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M

  composer:
    image: composer:latest
    container_name: pof_composer
    volumes:
      - ./power-of-families:/var/www/html/wp-content/themes/power-of-families
    working_dir: /var/www/html/wp-content/themes/power-of-families

volumes:
  wordpress:
  db_data: