version: '3.8'

services:
  wordpress:
    build: 
      context: .
      dockerfile: docker/wordpress.dockerfile
    # image: wordpress:5.1, php:7.4 # TT version as of 2/2024: https://support.tigertech.net/wordpress-version
    container_name: pof_wordpress
    depends_on:
      - db
      - phpmyadmin
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: pofuser
      WORDPRESS_DB_PASSWORD: pofpass
      WORDPRESS_DB_NAME: poweroffamilies
      WORDPRESS_TABLE_PREFIX: wp_
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    volumes:
      - ./wordpress:/var/www/html
      - ./power-of-families-theme:/var/www/html/wp-content/themes/power-of-families
      - ./pof-theme:/var/www/html/wp-content/themes/pof-theme
      - ./pof-programs-plugin:/var/www/html/wp-content/plugins/pof-programs
      - ./pof-bloom-plugin:/var/www/html/wp-content/plugins/pof-bloom

  
  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    # links: 
    #   - mysql:db
    entrypoint: wp
    command: "--info"
    container_name: pof_wpcli
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html

  db:
    image: mariadb:10.5.21 # TT version as of 2/2024: https://support.tigertech.net/mysql-version
    container_name: pof_db
    restart: always
    environment:
      MYSQL_DATABASE: poweroffamilies
      MYSQL_USER: pofuser
      MYSQL_PASSWORD: pofpass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: pof_phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 1024M

  composer:
    image: composer:latest
    container_name: pof_composer
    volumes:
      - ./pof-theme:/var/www/html/wp-content/themes/pof-theme
    working_dir: /var/www/html/wp-content/themes/pof-theme

volumes:
  wordpress:
  db_data: